### ISSUE TITLE
Conversion from EssentialsX

### ISSUE THREAD

**Issue by EvilOlaf** [TheNewEconomy/TNE-Bukkit#157]
Hey there,

I ran out of ideas how to convert from `EssentialsX` YAML userdata to `TNE`.
So basically what I did was to put the whole `Essentials` folder into the `TheNewEconomy` folder as requested in the commented `config.yml` (however I noticed here https://github.com/TheNewEconomy/TNE-Bukkit/blob/5335790160a9a49b7e0e627abc64dbc159375426/src/com/github/tnerevival/core/conversion/impl/Essentials.java#L33 that TNE should gather the data from the default Essentials folder location anyways).
Then I restarted the server with following settings in TNEs `config.yml`:

```
[...]
  Database:
    Type: FlatFile
    Prefix: TNE
    Backup: true
    FlatFile:
      File: economy.tne
    Transactions:
      Cache: true
      Update: 600
    MySQL:
      Host: localhost
      Port: 3306
      Database: TheNewEconomy
      User: user
      Password: password
    H2:
      File: Economy
    SQLite:
      File: economy.db
  Conversion:
    Convert: true
    Name: Essentials
    Format: YAML
    Options:
      Host: localhost
      Port: 3306
      Database: sql_eco
      User: root
      Password: Password
```

When I start the server TNE seems not to try any conversion at all.
Startup log: https://pastebin.com/BkeLLzci
When checking my credits I have the default amount of $200.

```
>version
[10:47:03 INFO]: This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
>version vault
[10:45:03 INFO]: Vault version 1.5.6-b49
[10:45:03 INFO]: Vault is a Permissions & Economy API to allow plugins to more easily hook into these systems without needing to hook each individual system themselves.
[10:45:03 INFO]: Website: http://dev.bukkit.org/server-mods/vault/
[10:45:03 INFO]: Authors: cereal, Sleaker and mung3r
>version essentials
[10:45:41 INFO]: Essentials version 2.0.1-b469
[10:45:41 INFO]: Provides an essential, core set of commands for Bukkit.
[10:45:41 INFO]: Website: http://tiny.cc/EssentialsCommands
[10:45:41 INFO]: Authors: Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally, drtshock, vemacs and SupaHam
[10:45:41 INFO]: EssentialsSpawn version 2.0.1-b469
[10:45:41 INFO]: Provides spawn control commands, utilizing Essentials.
[10:45:41 INFO]: Website: http://tiny.cc/EssentialsCommands
[10:45:41 INFO]: Authors: Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology and KHobbits
>version theneweconomy
[10:45:46 INFO]: TheNewEconomy version 0.0.5.5
[10:45:46 INFO]: A feature-packed Bukkit Economy Plugin.
[10:45:46 INFO]: Author: creatorfromhell
>vault-info
[10:46:41 INFO]: [Vault] Vault v1.5.6-b49 Information
[10:46:41 INFO]: [Vault] Economy: TheNewEconomy [TheNewEconomy, Essentials Economy]
[10:46:41 INFO]: [Vault] Permission: SuperPerms [SuperPerms]
[10:46:41 INFO]: [Vault] Chat: None [null]
```

Tried latest official from spigotMC as well as self build from source with latest commit https://github.com/TheNewEconomy/TNE-Bukkit/commit/9fb09ab28b5c472b85c08f6785e4c2cc439b524c

Thank you for taking a look into that and proving a hint what I overlooked. Also if I missed a required information please let me know.

Best regards
Olaf

**Comment by creatorfromhell** [comment]
Everything looks configured correctly, I'll be running some local tests to see what happens.

**Comment by creatorfromhell** [comment]
Just a small update, I haven't run into any issues converting from Essentials as of yet, but I still have a few more ideas to test...

**Comment by EvilOlaf** [comment]
Retried using SQLite as storage for TNE which did not work. Seems to be deprecated anywas (https://github.com/TheNewEconomy/TNE-Bukkit/issues/107)
Also tried to use MySQL. The tables seem to be generated properly. Conversion still not happened. However what I have noticed is a delay while loading TNE when conversion is enabled.

```
[...]
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Database.MySQL.Host, main)
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Database.MySQL.Port, main)
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Database.MySQL.Database, main)
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Database.MySQL.User, main)
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Database.MySQL.Password, main)
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Database.Prefix, main)
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Database.H2.File, main)
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Database.SQLite.File, main)
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Database.MySQL.Host, main)
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Database.MySQL.Port, main)
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Database.MySQL.Database, main)
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Database.MySQL.User, main)
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Database.MySQL.Password, main)
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Database.Prefix, main)
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Database.H2.File, main)
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Database.SQLite.File, main)
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Database.Transactions.Update, main)
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Database.Type, main)
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Database.FlatFile.File, main)
[12:52:47] [Server thread/INFO]: [TheNewEconomy] Save file of version: 5.4 detected.
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Conversion.Name, main)
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Conversion.Options.Host, main)
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Conversion.Options.Port, main)
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Conversion.Options.Database, main)
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Conversion.Options.User, main)
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Conversion.Options.Password, main)
[12:52:47] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.Conversion.Format, main)
[12:54:18] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.AutoSaver.Interval, main)
[12:54:18] [Server thread/INFO]: [TheNewEconomy] [DEBUG MODE]ConfigurationManager.getValue(Core.AutoSaver.Interval, main)
[12:54:18] [Server thread/INFO]: [TheNewEconomy] The New Economy 0.0.5.3 has been enabled!
[12:54:18] [Server thread/INFO]: [TheNewEconomy] Executing with Java Version: 1.8.0_131
[...]
```
As you can see about one and a half minute delay between the last config read and the final enabled message.

**Comment by creatorfromhell** [comment]
Fixed with latest commit.

**Comment by EvilOlaf** [comment]
Conversion still does not happen for me. :/
The MySQL error above seems to be fixed though.

**Comment by EvilOlaf** [comment]
After more than three hours TNE managed to convert about 25000 names. However the balance of all accounts is 0.

The hole `conversion.yml` has more than 100k lines, therefore an excerpt only:
```
  ERCTV98:
    Survival:
      Default:
        Amount: '0'
  HitsLikeCuBiX:
    Survival:
      Default:
        Amount: '0'
  MrLasergurke2003:
    Survival:
      Default:
        Amount: '0'
  Zeref_Demons:
    Survival:
      Default:
        Amount: '0'
  Breccie:
    Survival:
      Default:
        Amount: '0'
  sponglehd:
    Survival:
      Default:
        Amount: '0'
  onecreek:
    Survival:
      Default:
        Amount: '0'
  Neitynator:
    Survival:
      Default:
        Amount: '0'
  ErikNoe:
    Survival:
      Default:
        Amount: '0'
  GreenMadnessFX:
    Survival:
      Default:
        Amount: '0'
  LeoroHD:
    Survival:
      Default:
        Amount: '0'
  Ari3sTh3Cr33p:
    Survival:
      Default:
        Amount: '0'
  KingMeth:
    Survival:
      Default:
        Amount: '0'
  Mario_1007:
    Survival:
      Default:
        Amount: '0'
  Logische_Dagi:
    Survival:
      Default:
        Amount: '0'
  XxM_KxX:
    Survival:
      Default:
        Amount: '0'
  Minegirl_26:
    Survival:
      Default:
        Amount: '0'
  BaraNoJabei:
    Survival:
      Default:
        Amount: '0'
  Arne1wey:
    Survival:
      Default:
        Amount: '0'
  DerKaputt:
    Survival:
      Default:
        Amount: '0'
  KaddeSkillz:
    Survival:
      Default:
        Amount: '0'
  LPmitKevGeilo:
    Survival:
      Default:
        Amount: '0'
  MC_HAMMER:
    Survival:
      Default:
        Amount: '0'
  xoALEXox:
    Survival:
      Default:
        Amount: '0'
  konsti_erik:
    Survival:
      Default:
        Amount: '0'
  krax2013:
    Survival:
      Default:
        Amount: '0'
  Ernten:
    Survival:
      Default:
        Amount: '0'
  xFenuh:
    Survival:
      Default:
        Amount: '0'
  Mazer_Senpai:
    Survival:
      Default:
        Amount: '0'
  xXMauricePvPXx:
    Survival:
      Default:
        Amount: '0'
  rburren:
    Survival:
      Default:
        Amount: '0'
  David883:
    Survival:
      Default:
        Amount: '0'
  Cr7_bice:
    Survival:
      Default:
        Amount: '0' 
```

**Comment by creatorfromhell** [comment]
Try the attached jar, it has been proven to work on FeConomy, Essentials, and BConomy as of last night as is of the latest commit to which is why this is closed.
[TNE.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/1066559/TNE.zip)

**Comment by EvilOlaf** [comment]
Retried with the provided jar and got the same result. `Amount:` is always `'0'`.
Maybe there is an issue with the worlds? I guess you tested with the default world `world`.
I do not have a world called `world`. My default world is called  `Survival`.

**Comment by creatorfromhell** [comment]
I've tested with multiple worlds to see how the multiworld would be affected.
